### ISSUE TITLE
Build failed in github action rust mode when as a  dependency

### ISSUE THREAD

**Issue by TakWolf** [dcuddeback/libudev-sys#5]
```
     Running `/home/runner/work/tge/tge/target/debug/build/libudev-sys-2c0cd69c2a7f8e70/build-script-build`
error: failed to run custom build command for `libudev-sys v0.1.4`

Caused by:
  process didn't exit successfully: `/home/runner/work/tge/tge/target/debug/build/libudev-sys-2c0cd69c2a7f8e70/build-script-build` (exit code: 101)
```

Maybe relative to:

https://github.com/dcuddeback/libudev-sys/issues/2

**Comment by dcuddeback** [comment]
@TakWolf There's no detail in this issue for me to work with. Also the issue you link to has been fixed for almost three years. I think you need to do some more research on your end before opening an issue. I'm closing this as non-actionable.
